esphome:
  name: soundsensor
  friendly_name: SoundSensor
  platformio_options:
    board_build.flash_mode: dio
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino
    # Enable logging
logger:
# Enable Home Assistant API
api:
ota:
  platform: esphome
wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "skynet-subsidiary_001"
    password: !secret ota
improv_serial:
captive_portal:
# Example configuration entry
web_server:
  port: 80
globals:
  - id: esphome_sensitivity
    type: float
    initial_value: '36.5'
    restore_value: yes
  - id: esphome_volume
    type: int
binary_sensor:
  - platform: gpio
    pin:
      number: 3
      mode:
        input: true
        pullup: false
    id: sound_sensor
light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: ALWAYS_OFF
