esphome:
  name: soundsensor
  friendly_name: SoundSensor
  platformio_options:
    board_build.flash_mode: dio
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino
    # Enable logging
logger:
  level: debug
# Enable Home Assistant API
api:
ota:
  platform: esphome
wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password
improv_serial:
captive_portal:
# Example configuration entry
web_server:
  port: 80
binary_sensor:
  - platform: gpio
    pin:
      number: 9
      # pin is low when comparator is triggered
      inverted: true
      mode:
        input: true
        pullup: false
    id: sound_sensor
    icon: "mdi:bell-ring"
    on_press:
      then:
        - logger.log: "Sound Sensor triggered"
light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: ALWAYS_OFF
