name: esphome-build
on:
  push:
    branches: main
    tags: ['v*.*.*']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create secrets file with null values
        run: cp secrets{.github-build,}.yaml
      - name: ESPHome Builder
        uses: esphome/build-action@v4
        with:
          yaml-file: esphome.yaml
          release-url: "https://github.com/spezifisch/esphome-entry"
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: github-build*/*
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/*
