name: esphome-build
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create annotation for build error
        run: cp secrets{.example,}.yaml
      - name: ESPHome Builder
        uses: esphome/build-action@v4.0.3
        with:
          yaml-file: github-build.yaml
          release-url: "https://github.com/spezifisch/esphome-entry"
      - uses: actions/upload-artifact@v4
        with:
          name: esphome-build-output
          path: github-build*/*

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: esp-build-output/*
